#Requires -Version 7.4

<#
.SYNOPSIS
    Fails when a compiled gh aw lock file pins github/gh-aw-actions to a different version than its compiler.
.DESCRIPTION
    github/gh-aw-actions is version-locked to the gh aw compiler that produced each `.lock.yml`. A newer setup action can drop scripts that an older lock still calls. Every `uses: github/gh-aw-actions/...` pin must match the lock's compiled version and the SHA recorded in its gh-aw manifest header. Change these pins only by recompiling with `gh aw compile`.
#>

[CmdletBinding()]
param(
    [string] $Root = (Join-Path $PSScriptRoot '..')
)

Set-StrictMode -Version 3.0
$ErrorActionPreference = 'Stop'

$Root = (Resolve-Path -LiteralPath $Root).Path
$lockFiles = @(Get-ChildItem -LiteralPath $Root -Recurse -Force -File -Filter '*.lock.yml' | Where-Object { $_.FullName -notmatch '[\\/]\.git[\\/]' } | Sort-Object -Property FullName)
if ($lockFiles.Count -eq 0) {
    throw [System.InvalidOperationException]::new("No .lock.yml files found under $Root.")
}

$failures = [System.Collections.Generic.List[string]]::new()
foreach ($file in $lockFiles) {
    $relative = [System.IO.Path]::GetRelativePath($Root, $file.FullName).Replace('\', '/')
    $text = [System.IO.File]::ReadAllText($file.FullName)

    $header = [regex]::Match($text, '(?m)^# This file was automatically generated by gh-aw \((?<version>v[^)]+)\)')
    if (-not $header.Success) {
        $failures.Add("$relative : missing the gh-aw compiler version header.")
        continue
    }
    $compiled = $header.Groups['version'].Value

    $manifest = [regex]::Match($text, '(?m)^# gh-aw-manifest: (?<json>\{.*\})\s*$')
    $manifestPins = @{}
    if ($manifest.Success) {
        foreach ($action in @(($manifest.Groups['json'].Value | ConvertFrom-Json).actions)) {
            $manifestPins[$action.repo] = $action
        }
    }

    $pins = [regex]::Matches($text, '(?m)^\s*(?:-\s+)?uses:\s+(?<repo>github/gh-aw-actions/[^@\s]+)@(?<sha>[0-9a-f]{40})(?:\s+#\s+(?<tag>\S+))?')
    foreach ($pin in $pins) {
        $repo = $pin.Groups['repo'].Value
        $sha = $pin.Groups['sha'].Value
        $tag = $pin.Groups['tag'].Value
        if ($tag -ne $compiled) {
            $failures.Add("$relative : $repo@$sha is tagged '$tag' but the lock was compiled with gh aw $compiled.")
        }

        if (-not $manifestPins.ContainsKey($repo)) {
            $failures.Add("$relative : $repo is missing from the gh-aw manifest header.")
        } elseif ($manifestPins[$repo].sha -ne $sha -or $manifestPins[$repo].version -ne $compiled) {
            $failures.Add("$relative : $repo@$sha does not match the manifest pin $($manifestPins[$repo].sha) ($($manifestPins[$repo].version)) for gh aw $compiled.")
        }
    }

    Write-Host "Checked $($pins.Count) gh-aw-actions pin(s) in $relative against gh aw $compiled"
}

if ($failures.Count -gt 0) {
    throw [System.InvalidOperationException]::new(
        "gh-aw-actions pins must match the gh aw compiler. Recompile with ``gh aw compile`` instead of bumping them:`n$($failures -join "`n")"
    )
}
